name: build site

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content
        with:
          submodules: true
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' #install the python version needed    
      - name: Install dependencies
        run:
          python -m pip install --upgrade pip
          pip install -r requirements.txt    
      - name: get bibtex
        run:
          python bibliographer-github-1.py
      - name: convert bibtex to CSL JSON
        uses: docker://pandoc/core:3.2
        with:
          args: >-  # allows you to break string into multiple lines
            -f
            bibtex
            output.bib
            -t
            csljson
            -o
            middle.json
      - name: convert bibtex to json and add some extras
        run:
          python bibliographer-github-2.py  
      - name: populate
        run:
          python populate.py
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm install
      - name: build nmp
        run: npm run build --if-present
      - name: get output in the repo
        uses: stefanzweifel/git-auto-commit-action@v5
      - name: Deploy to my domain
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.FTP_USERNAME }}
          server: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT }}
          local_path: './docs/*'
          remote_path: '/fmuro'
          sftp_only: true
          password: ${{ secrets.FTP_PASSWORD }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs
          
# Deployment job to GutHub Pages
  deploy:
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4